namespace Clean.Architecture.Web.ApiModels;

/// <summary>
/// TODO.
/// ApiModel DTOs are used by ApiController classes and are typically kept in a side-by-side folder.
/// </summary>
public class ProjectDTO : CreateProjectDTO
{
  /// <summary>
  /// Initializes a new instance of the <see cref="ProjectDTO"/> class.
  /// </summary>
  /// <param name="id">TODO LATER.</param>
  /// <param name="name">TODO LATER2.</param>
  /// <param name="items">TODO LATER3.</param>
  public ProjectDTO(int id, string name, List<ToDoItemDTO>? items = null)
    : base(name)
  {
    Id = id;
    Items = items ?? new List<ToDoItemDTO>();
  }

  /// <summary>
  /// Gets or sets Id of the ProjectDTO.
  /// </summary>
  public int Id { get; set; }

  /// <summary>
  /// Gets or sets the to-do items of the project DTO.
  /// </summary>
  public List<ToDoItemDTO> Items { get; set; }
}

/// <summary>
/// TODO.
/// Creation DTOs should not include an ID if the ID will be generated by the back end.
/// </summary>
public abstract class CreateProjectDTO
{
  /// <summary>
  /// Initializes a new instance of the <see cref="CreateProjectDTO"/> class.
  /// </summary>
  /// <param name="name">TODO LATER.</param>
  protected CreateProjectDTO(string name)
  {
    Name = name;
  }

  /// <summary>
  /// Gets or sets the Name of the ProjectDTO.
  /// </summary>
  public string Name { get; set; }
}
